import {
    PersonOutline as PersonIcon,
    BookOutline as BookIcon,
    BookmarkOutline as BookmarkIcon,
    VolumeHighOutline as VolumeIcon,
    ImageOutline as ImageIcon,
    HomeOutline as HomeIcon,
    TextOutline as TextIcon,
    VideocamOutline as VideoIcon,
    LogoMarkdown as MarkdownIcon,
    ChatboxOutline as ChatboxIcon,
    SquareOutline as SquareIcon,
    Square as SquareFullIcon,
    ChatboxEllipsesOutline as ChatboxEIcon,
    ArrowBackOutline as ArrowBackIcon,
    NotificationsOutline as NoticeIcon,
} from '@vicons/ionicons5'

export const Icons = {
    person: PersonIcon,
    book: BookIcon,
    bookmark: BookmarkIcon,
    volume: VolumeIcon,
    image: ImageIcon,
    home: HomeIcon,
    text: TextIcon,
    video: VideoIcon,
    markdown: MarkdownIcon,
    chatbox: ChatboxIcon,
    chatboxE: ChatboxEIcon,
    square: SquareIcon,
    squareFull: SquareFullIcon,
    arrowBack: ArrowBackIcon,
    notice: NoticeIcon,
}
